### ISSUE TITLE
travis and appveyor should move the bulk of its logic to running a nim file

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10041]
something like this:
## add koch options: ci_script, before_deploy
so that these work:
```
nim c -r koch ci_script
nim c -r koch c_before_deploy
```
then update .travis.yml to just call it:
```
sudo: false
language: c

dist: trusty

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libsdl1.2-dev
    - libgc-dev
    - libsfml-dev

before_script:
  - set -e
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then unset -f cd; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then shell_session_update() { :; }; fi
  # or maybe: sh build_all.sh
  - git clone --depth 1 https://github.com/nim-lang/csources.git
  - cd csources
  - sh build.sh
  - cd ..
  - export PATH=$(pwd)/bin${PATH:+:$PATH}
script:
  - nim c -r koch ci_script

before_deploy:
  - nim c -r koch ci_before_deploy
deploy:                         # https://nim-lang.github.io/Nim
  provider: pages
  # local-dir *has* to be a relative path from the repo root.
  local-dir: "doc/html"
  skip-cleanup: true
  github-token: "$GITHUB_OAUTH_TOKEN"
  keep-history: false
  on:
    branch: devel
```

and similar with appveyor

## benefits
* avoid code duplication as much as possible bw appveyor and travis
* make it easier to run locally what's being run in travis
* make it easier to port to other CI platforms since all we'd need is a working `nim` compiler
* would allow reviving https://github.com/nim-lang/Nim/pull/8552 but doing it in pure nim
