### ISSUE TITLE
Documentation Regression no runnableExamples on devel

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#14491]
[Documentation Bleeding Edge](https://nim-lang.github.io/Nim/theindex.html) is not showing `runnableExamples`,
it has `runnableExamples`, and used to show `runnableExamples` so is a Regression.

- Bug: https://nim-lang.github.io/Nim/decls.html
- Ok: https://nim-lang.org/docs/decls.html
- Code: https://github.com/nim-lang/Nim/blob/devel/lib/std/decls.nim#L7

---
- Bug: https://nim-lang.github.io/Nim/with.html
- Ok: https://nim-lang.org/docs/with.html
- Code: https://github.com/nim-lang/Nim/blob/devel/lib/std/with.nim#L24

You can check the rest of the modules, it does repro too.

**Comment by timotheecour** [comment]
fixed by https://github.com/nim-lang/Nim/pull/14439, https://nim-lang.github.io/Nim/decls.html now shows runnableExamples
a push is needed to specific paths in order to have docs be rebuilt, see `$nim/.github/workflows/ci_docs.yml` 
```
name: Nim Docs CI
on:
  push:
    # Run only on changes on these files
    paths:
      - 'lib/**.nim'
      - 'doc/**.rst'
      - 'doc/nimdoc.css'
      - '.github/workflows/ci_docs.yml'

  pull_request:
    # Run only on changes on these files
    paths:
      - 'lib/**.nim'
      - 'doc/**.rst'
      - '.github/workflows/ci_docs.yml'
```
we should show git hash in devel docs, otherwise hard to tell which version was docgen'd
