### ISSUE TITLE
[tester] autotester should add OSX; eg using macincloud or macstadium

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8493]
* regressions on mac won't be caught until someone figures it out the hard way
* eg: https://github.com/nim-lang/Nim/pull/8492 fixes a long standing bug that affected only OSX, but was never actually tested 
* see https://github.com/nim-lang/Nim/pull/8411 for another example
* probably lots of other existing issues that affect only OSX, eg: when I have a PR, I can't test it locally on my mac because it fails even from devel branch: `FAILURE! total: 105 passed: 85 skipped: 0`

## proposal
* use https://www.macincloud.com/
* or use https://www.macstadium.com/usecases/
> With MacStadium, Travis CI launched a scalable hosted private cloud for their OS X and iOS build jobs on dedicated Mac hardware

**Comment by Araq** [comment]
I've been waiting for Travis' OSX support to become stable.

**Comment by mratsim** [comment]
This script has been working fine to build Nim from devel on Travis for the past 6 months. The only issue is the delay, Travis OSX machine sometimes queue jobs for hour.

https://github.com/status-im/nimbus/blob/master/.travis.yml (you can remove rocksdb install part and Status patches)

```yaml
    - os: osx
      before_install:
        - brew update
        - brew install rocksdb
        # - brew install gcc

        - git clone https://github.com/nim-lang/nim.git
        - cd nim
        - git remote add statusim https://github.com/status-im/nim.git
        - git fetch statusim
        - git config --global user.email "you@example.com"
        - git config --global user.name "Your Name"
        - for b in $(git branch -a --list 'statusim/status-autopatch-*'); do git merge $b; done
        - git clone --depth 1 https://github.com/nim-lang/csources.git
        - cd csources
        - sh build.sh
        - cd ..
        - export PATH=$PWD/bin:$PATH
        - nim c koch
        - ./koch boot -d:release
        - ./koch nimble
        - cd ..
```
